name: Publish Module to Powershell Gallery

# Controls when the action will run. 
on:
  push:
    tags:
    - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v2
        
      - name: Publish Module to PowerShell Gallery
        uses: pcgeek86/publish-powershell-module-action@v19
        with:
          modulePath: GitHubModuleInstaller
          NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
